name: Deploy to GitHub Pages (Development)

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # ou a versão do Node.js compatível com o Next.js

      - name: Install dependencies
        run: npm install

      - name: Build and export Next.js project
        run: |
          npm run build
          npm run export
        working-directory: .

      - name: Add .nojekyll file
        run: touch out/.nojekyll
        working-directory: .

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b gh-pages-dev
          git add .
          git commit -m "Build and export Next.js project for dev"
          git push origin gh-pages-dev
        working-directory: .
