# Este fluxo de trabalho usa ações que não são certificadas pelo GitHub.
# Elas são fornecidas por terceiros e são regidas por
# termos de serviço, política de privacidade e documentação de suporte
# separados.

# Exemplo de fluxo de trabalho para construir e implantar um site Jekyll no GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Executa em push para a branch padrão
  push:
    branches: ["main"]

  # Permite executar este fluxo de trabalho manualmente na guia "Actions"
  workflow_dispatch:

# Define as permissões do token GITHUB_TOKEN para permitir a implantação no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea, ignorando as execuções enfileiradas entre a execução em andamento e a última enfileirada.
# No entanto, NÃO cancele execuções em andamento, pois queremos permitir que essas implantações de produção sejam concluídas.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construção
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Não necessário com um arquivo .ruby-version
          bundler-cache: true # executa 'bundle install' e armazena em cache as gems instaladas automaticamente
          cache-version: 0 # Incremente este número se precisar baixar novamente as gems armazenadas em cache
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        # Saída para o diretório './_site' por padrão
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Carrega automaticamente um artefato do diretório './_site' por padrão
        uses: actions/upload-pages-artifact@v3

  # Job de implantação
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
