name: Deploy Next.js site to Pages - Dev

on:
  push:
    branches: ['dev']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configura o ambiente Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: npm

      # Configura o Next.js
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: build

      # Instala as dependências, incluindo o sharp para otimização de imagens
      - name: Install dependencies and sharp for image optimization
        run: |
          npm install
          npm install sharp

      # Constrói com o Next.js
      - name: Build with Next.js
        run: |
          npx --no-install next build
          npx next telemetry disable

      # Faz o upload do artefato para GitHub Pages Dev
      - name: Upload GitHub Pages Dev artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages-dev
          path: ./build

  deploy:
    environment:
      name: github-pages-dev
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Baixa o artefato
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages-dev
          path: ./build

      # Implementa no GitHub Pages Dev
      - name: Deploy to GitHub Pages Dev Dev Dev
        id: deployment
        uses: actions/deploy-pages@v3
