name: Pull Request Intregation

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: npm install
      
      - name: Update
        run: npm update
      
      - name: Formatando Padrão Lint e Prettier
        run: npm run format

      - name: Install dependencies
        run: npm ci
        env:
          CI: false
