name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Add package.json changes
        run: git add package.json

      - name: Commit package.json changes
        run: |
          git config --global user.email "jon.1lima@hotmail.com"
          git config --global user.name "JhowSL"
          git commit -m "chore: bump version [skip ci]" || echo "No changes to commit"
          git push
