name: Versioning Workflow

on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        env:
          CI: false
      - name: Ensure Clean Working Directory
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Working directory is not clean, stashing changes..."
            git stash --include-untracked
          fi
      - name: Bump version
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$branch" = "main" ]; then
            npm version major -m "chore(release): %s"
          elif [ "$branch" = "dev" ]; then
            npm version minor -m "chore(release): %s"
          else
            npm version patch -m "chore(release): %s"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Push tags
        run: |
          if git pull --rebase; then
            git push --follow-tags
          else
            git rebase --abort
            echo "Rebase failed due to conflicts, aborting."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
